version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "Dependencies"
      - "CI"
    commit-message:
      prefix: "chore"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "actions/*"
        update-types:
          - "minor"
          - "patch"
